services:

  python-service:
    container_name: energia-api
    build:
      context: .
      dockerfile: ./fastapi/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi/.env
    volumes:
      - ./fastapi:/app

  gateway:
    container_name: energia-gateway
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./gateway/.env
    depends_on:
      - python-service
    volumes:
      - ./gateway:/app
      - /app/node_modules
  
  mcp-fastapi:
    container_name: energia-mcp-fastapi
    build:
      context: .
      dockerfile: mcp_fastapi/Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./mcp_fastapi/.env
    volumes:
      - ./mcp_fastapi:/app

