services:

  python-service:
    image: emfall/energia-python
    ports:
      - "8000:8000"
    environment:
      HOST: 0.0.0.0
      PORT: 8000

  gateway:
    image: emfall/energia-gateway
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000