services:

  python-service:
    container_name: energia-api
    build:
      context: .
      dockerfile: ./ms_dijkstra/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./ms_dijkstra/.env
    volumes:
      - ./ms_dijkstra:/app

  ms_metier:
    container_name: metier-service
    build:
      context: .
      dockerfile: ./ms_metier/Dockerfile
    ports:
      - "8004:8004"
    env_file:
      - ./ms_metier/.env
    depends_on :
      - python-service
    volumes:
      - ./ms_metier:/app

  gateway:
    container_name: energia-gateway
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./gateway/.env
    depends_on:
      - python-service
    volumes:
      - ./gateway:/app
      - /app/node_modules
  
  mcp-fastapi:
    container_name: energia-mcp-fastapi
    build:
      context: .
      dockerfile: ms_mcp/Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./ms_mcp/.env
    volumes:
      - ./ms_mcp:/app

