[project]
name = "mcp-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nassim", email = "achnassim34@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "fastapi[standard]>=0.141.1",
    "starlette>=1.6.0",
]

[project.scripts]
mcp-fastapi = "mcp_fastapi:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
